=== ayoubdkhissi/MobDev/app/xml/factures/factures.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="factures" type="facturesType"/>


    <!--Defined Types:-->
    <!--factures is a sequence of facture with no limit on occurrences-->
    <xs:complexType name="facturesType">
        <xs:sequence>
            <xs:element name="facture" type="factureType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--facture is a sequence of elements that are obligatory and should appear on that exact order-->
    <xs:complexType name="factureType">
        <xs:sequence>
            <xs:element name="factureID" type="xs:integer"/>
            <xs:element name="userID" type="xs:integer" />
            <xs:element name="userName" type="userNameType" />
            <xs:element name="userPhone" type="phoneNumberType"/>
            <xs:element name="date" type="xs:dateTime"/> <!--date format: yyyy-mm-ddThh:min:sec-->
            <xs:element name="products" type="productsType"/>
            <xs:element name="totalPrice" type="unsignedDouble"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="userNameType">
        <xs:sequence>
            <xs:element name="userFirstName" type="xs:string"/>
            <xs:element name="userLastName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!--Restriction on phone number-->
    <xs:simpleType name="phoneNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{10}" />
        </xs:restriction>
    </xs:simpleType>

    <!--ProductsType definition: sequence of products-->
    <xs:complexType name="productsType">
        <xs:sequence>
            <xs:element name="product" type="productType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--ProductType definition-->
    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="quantity" type="xs:unsignedInt"/>
            <xs:element name="unitPrice" type="unsignedDouble"/>
            <xs:element name="allPrice" type="unsignedDouble"/>
        </xs:sequence>
    </xs:complexType>

    <!--unsignedDouble type definition-->
    <xs:simpleType name="unsignedDouble">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== ayoubdkhissi/MobDev/app/xml/factures/factures.xml
<?xml version="1.0" encoding="utf-8"?>
<factures xmlns="https://www.w3schools.com"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.w3schools.com factures.xsd">

    <facture>
        <factureID>1</factureID>
        <userID>2</userID>
        <userFirstName>Ayoub</userFirstName>
        <userLastName>Dkhissi</userLastName>
        <userPhone>0698989898</userPhone>
        <date>2021-07-15T20:12:00</date>
        <products>
            <product>
                <description>Phone SAMSUNG GALAXY S25</description>
                <quantity>5</quantity>
                <unitPrice>10000</unitPrice>
                <allPrice>50000</allPrice>
            </product>
            <product>
                <description>laptop HP Pavillon i7-10075H, 16Ram, 512SSD, Nvidia RTX-2060, 14.5 inches, Camera 'BisonCam,NB Pro'</description>
                <quantity>1</quantity>
                <unitPrice>15000</unitPrice>
                <allPrice>15000</allPrice>
            </product>
        </products>
        <totalPrice>65000</totalPrice>
    </facture>
    <facture>
        <factureID>2</factureID>
        <userID>1</userID>
        <userFirstName>Walid</userFirstName>
        <userLastName>Omari</userLastName>
        <userPhone>0665656565</userPhone>
        <date>2002-05-30T09:00:00</date>
        <products>
            <product>
                <description>laptop HP Pavillon i7-10075H, 16Ram, 512SSD, Nvidia RTX-2060, 14.5 inches, Camera 'BisonCam,NB Pro'</description>
                <quantity>3</quantity>
                <unitPrice>15000</unitPrice>
                <allPrice>45000</allPrice>
            </product>
        </products>
        <totalPrice>45000</totalPrice>
    </facture>
</factures>
