=== ayoubdkhissi/MobDev/app/xml/products/products.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="products" type="productsType"/>

    <!--Defined Types-->

    <!--products is a sequence of product with no limit on occurrences-->
    <xs:complexType name="productsType">
        <xs:sequence>
            <xs:element name="product" type="productType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--product is a sequence of elements that are obligatory and should appear on that exact order-->
    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="productID" type="xs:unsignedInt"/>
            <xs:element name="type" type="productTypeType"/>
            <xs:element name="mark" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="cpu" type="xs:string"/>
            <xs:element name="ram" type="xs:string"/>
            <xs:element name="storage" type="xs:string"/>
            <xs:element name="gpu" type="xs:string"/>
            <xs:element name="size" type="unsignedDouble"/>
            <xs:element name="camera" type="xs:string"/>
            <xs:element name="price" type="unsignedDouble"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="img" type="imgType"/>
        </xs:sequence>
    </xs:complexType>

    <!--Restriction on type : must be 'laptop' or 'phone' we can add more later...-->
    <xs:simpleType name="productTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="laptop"/>
            <xs:enumeration value="phone"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Restriction on price : must be positive-->
    <xs:simpleType name="unsignedDouble">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <!--img is an empty tag with one attribute size-->
    <xs:complexType name="imgType">
        <xs:attribute name="src" type="xs:string"/>
    </xs:complexType>


</xs:schema>

=== ayoubdkhissi/MobDev/app/xml/products/products.xml
<?xml version="1.0" encoding="utf-8"?>
<products xmlns="https://www.w3schools.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://www.w3schools.com products.xsd">


    <product>
        <productID>1</productID>
        <type>laptop</type>
        <mark>HP</mark>
        <model>Pavillon</model>
        <cpu>Intel Core i7-10075H (10th gen)</cpu>
        <ram>16 GB DDR4 RAM</ram>
        <storage>512 GB SSD</storage>
        <gpu>Intel UHD</gpu>
        <size>14.5</size>
        <camera>BisonCam,NB Pro</camera>
        <price>11000</price>
        <img src="public/uploads/product1.jpg"/>
    </product>

    <product>
        <productID>2</productID>
        <type>phone</type>
        <mark>SAMSUNG</mark>
        <model>GALAXY S25U</model>
        <cpu>Cortex A55</cpu>
        <ram>1 GB RAM</ram>
        <storage>256 GB</storage>
        <gpu>Mali-G77 MP11</gpu>
        <size>14.5</size>
        <camera>108 megapixel</camera>
        <price>10000</price>
        <img src="public/uploads/product2.jpg"/>
    </product>

    <product>
        <productID>3</productID>
        <type>phone</type>
        <mark>Apple</mark>
        <model>iphone X</model>
        <cpu>Apple A11 bionic</cpu>
        <ram>3 GB RAM</ram>
        <storage>256 GB</storage>
        <gpu> Apple GPU (three-core graphics) </gpu>
        <size>7.7</size>
        <camera>12MP wide-angle </camera>
        <price>7000</price>
        <img src="public/uploads/product3.png"/>
    </product>

    <product>
        <productID>4</productID>
        <type>laptop</type>
        <mark>GigaByte</mark>
        <model> AORUS 5kb laptop</model>
        <cpu>i7-10750H 10th Gen 6 Core™</cpu>
        <ram>16 GB RAM</ram>
        <storage>512 GB SSD</storage>
        <gpu> NVIDIA RTX2060 </gpu>
        <size>14.5</size>
        <camera>Nahimic3 3D WebCam </camera>
        <price>12000</price>
        <img src="public/uploads/product4.jpg"/>
    </product>

    <product>
        <productID>5</productID>
        <type>laptop</type>
        <mark>Asus</mark>
        <model> ASUS TUF Dash F15</model>
        <cpu>11th Gen Intel® Core™ i7-11375H</cpu>
        <ram>32GB of DDR4-3200 RAM</ram>
        <storage>1 TB SSD</storage>
        <gpu> GeForce RTX™ 3070 GPU  </gpu>
        <size>19.9</size>
        <camera>WebCam ProHD</camera>
        <price>15000</price>
        <img src="public/uploads/product5.jpg"/>
    </product>

    <product>
        <productID>6</productID>
        <type>laptop</type>
        <mark>HP</mark>
        <model>OMEN 17 LAPTOP</model>
        <cpu>11th Gen Intel® Core™ i7-11800H</cpu>
        <ram>32 GB DDR4-3200 RAM</ram>
        <storage>512 GB SSD</storage>
        <gpu>NVIDIA® GeForce RTX™ 3070 Mobile</gpu>
        <size>17.3</size>
        <camera>HP Wide Vision 720p HD camera</camera>
        <price>20000</price>
        <img src="public/uploads/product6.png"/>
    </product>

    <product>
        <productID>7</productID>
        <type>laptop</type>
        <mark>HP</mark>
        <model>Spectre x360 Convertible</model>
        <cpu>11th Gen Intel® Core™ i7-1165G7</cpu>
        <ram>16 GB DDR RAM</ram>
        <storage>512 GB Intel® SSD</storage>
        <gpu>Intel® Iris® Xe Graphics</gpu>
        <size>14.3</size>
        <camera>HP Wide Vision 720p HD camera</camera>
        <price>13000</price>
        <img src="public/uploads/product7.png"/>
    </product>

    <product>
        <productID>8</productID>
        <type>phone</type>
        <mark>Apple</mark>
        <model>iPhone 11</model>
        <cpu>Hexa-core(2x2.65 GHz Lightning)</cpu>
        <ram>4 GB RAM</ram>
        <storage>256 GB</storage>
        <gpu> Apple GPU (4-core graphics) </gpu>
        <size>6.1</size>
        <camera>12 MP, 4K f/1.8, 26mm X3 </camera>
        <price>7000</price>
        <img src="public/uploads/product8.jpg"/>
    </product>

</products>
