=== ayoubdkhissi/MobDev/app/xml/users/users.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    
    <xs:element name="users" type="usersType"/>


    <!--Defined Types-->

    <!--users is a sequence of user with no limit on occurrences-->
    <xs:complexType name="usersType">
        <xs:sequence>
            <xs:element name="user" type="userType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--user is a sequence of elements that are obligatory and should appear on that exact order-->
    <xs:complexType name="userType">
        <xs:sequence>
            <xs:element name="userID" type="xs:unsignedInt"/>
            <xs:element name="username" type="usernameType"/>
            <xs:element name="firstName" type="FLNameType"/>
            <xs:element name="lastName" type="FLNameType"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="phone" type="phoneNumberType"/>
            <xs:element name="img" type="imgType"/>
        </xs:sequence>
        <xs:attribute name="rank" type="rankType" use="required" default="costumer"/>
    </xs:complexType>

    <!--Rank attribute type: should only take one of these values: 'costumer', 'admin', 'manager'-->
    <xs:simpleType name="rankType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="customer"/>
            <xs:enumeration value="admin"/>
            <xs:enumeration value="manager"/>
        </xs:restriction>
    </xs:simpleType>
    <!--Restriction on first name and last name: should not contain any numerical character-->
    <xs:simpleType name="FLNameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]+"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Restriction on username: should not have any white spaces-->
    <xs:simpleType name="usernameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^\s]+"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Restriction on email: must respect the email pattern-->
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z_.?]+@[a-zA-Z_.?].+[a-z]+"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Restriction on phone number: must respect the phone number pattern-->
    <xs:simpleType name="phoneNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}" />
        </xs:restriction>
    </xs:simpleType>

    <!--img is an empty tag with one attribute size-->
    <xs:complexType name="imgType">
        <xs:attribute name="src" type="xs:string"/>
    </xs:complexType>



</xs:schema>

=== ayoubdkhissi/MobDev/app/xml/users/users.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns="https://www.w3schools.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://www.w3schools.com users.xsd">
    <user>
        <userID>1</userID>
        <username>walid_omari</username>
        <firstName>Walid</firstName>
        <lastName>Omari</lastName>
        <email>Omari.walid@gmail.com</email>
        <password>Admin@123</password>
        <phone>0665656565</phone>
        <img src="/res/image.jpeg"/>
    </user>
    <user>
        <userID>2</userID>
        <username>ayoub_dkhissi</username>
        <firstName>Ayoub</firstName>
        <lastName>Dkhissi</lastName>
        <email>dkhissi.ayoub@gmail.com</email>
        <password>Admin@123555</password>
        <phone>0698989898</phone>
        <img src="/res/tinyWiny.jpeg"/>
    </user>
</users>
